name: KiloWatts Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  dusk-php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare The Environment
        run: cp .env.example .env
      - name: Create Database
        run: |
          sudo systemctl start mysql
          mysql --user="root" --password="root" -e "CREATE DATABASE kilo-watts character set UTF8mb4 collate utf8mb4_bin;"
      - name: Remove composer.lock
        run: rm composer.lock
      - name: Install Composer Dependencies
        run: composer install --no-scripts --no-progress --no-suggest --prefer-dist --optimize-autoloader --ignore-platform-reqs
      - name: Generate Application Key
        run: php artisan key:generate
      - name: Seed the database
        run: php artisan migrate:fresh --seed
      - name: Run Laravel Server
        run: php artisan serve &
      - name: Run unit and feature tests
        run: phpunit
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: tests/Browser/screenshots
      - name: Upload Console Logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: console
          path: tests/Browser/console
