name: KiloWatts Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  dusk-php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare The Environment
        run: cp .env.pipeline .env
      - name: Create Database
        run: |
          sudo systemctl start mysql
          mysql --user="root" --password="root" -e "CREATE DATABASE kilo_watts character set UTF8mb4 collate utf8mb4_bin;"
      - name: Remove composer.lock
        run: rm composer.lock
      - name: Install Composer Dependencies
        run: composer install --no-scripts --no-progress --no-suggest --prefer-dist --optimize-autoloader --ignore-platform-reqs
      - name: Generate Application Key
        run: php artisan key:generate
      - name: Migrate the database
        run: php artisan migrate:fresh
      - name: Create sqlite database
        run: touch database/database.sqlite
      - name: Run unit and feature tests
        run: phpunit
